# Generated by Django 5.1.3 on 2024-11-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('pais_origem', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('pais_origem', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('Cinéfilo', 'Cinéfilo'), ('Usuário Casual', 'Usuário Casual'), ('Pai/Mãe', 'Pai/Mãe'), ('Estudante de Cinema', 'Estudante de Cinema'), ('Apreciador de Séries', 'Apreciador de Séries')], max_length=50)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('conta_verificada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.ator')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano_lancamento', models.IntegerField(blank=True, null=True)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('genero', models.JSONField()),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('avaliacao_media', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('url_poster', models.CharField(blank=True, max_length=255, null=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filmes.diretor')),
                ('elenco', models.ManyToManyField(through='filmes.Elenco', to='filmes.ator')),
            ],
        ),
        migrations.AddField(
            model_name='elenco',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elenco_filmes', to='filmes.filme'),
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_recomendacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_sugestao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPreferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generos_preferidos', models.JSONField()),
                ('diretores_preferidos', models.JSONField()),
                ('atores_preferidos', models.JSONField()),
                ('restricoes_conteudo', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filmes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('tipo_notificacao', models.CharField(choices=[('novo filme', 'novo filme'), ('atualização de catálogo', 'atualização de catálogo')], max_length=50)),
                ('status', models.CharField(choices=[('lida', 'lida'), ('não lida', 'não lida')], default='não lida', max_length=20)),
                ('data_notificacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaFilmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lista', models.CharField(choices=[('Para Assistir', 'Para Assistir'), ('Assistido', 'Assistido')], max_length=20)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Assistido', 'Assistido'), ('Pausado', 'Pausado')], max_length=20)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Discussao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico_discussao', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracoesConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencia_idioma', models.CharField(blank=True, max_length=50, null=True)),
                ('notificacoes_ativadas', models.BooleanField(default=True)),
                ('preferencia_tema', models.CharField(choices=[('claro', 'claro'), ('escuro', 'escuro')], default='claro', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filmes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.usuario')),
            ],
        ),
    ]
